# Generated by Django 4.0.4 on 2022-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecord', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('book', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Dev',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
