# Generated by Django 4.0.4 on 2022-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
